from typing import Union, Tuple
import pathlib
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
            
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if pathlib.Path(data_fname).is_file():
            self.data_fname=pathlib.Path(data_fname)
        else:
            raise ValueError

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data = pd.read_json(self.data_fname)
    
    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Calculates and plots the age distribution of the participants.
        Returns a tuple containing two numpy arrays:
        The first item being the number of people in a given bin.
        The second item being the bin edges.
        """
        bins = np.linspace(0,100,11)
        return np.histogram(self.data['age'], bins = bins)
    
    def remove_rows_without_mail(self) -> pd.DataFrame:
        """
        Checks self.data for rows with invalid emails, and removes them.
        Returns the corrected DataFrame, i.e. the same table but with
        the erroneous rows removed and the (ordinal) index after a reset.
        """
        return self.data[self.data['email'].str.contains('@[a-zA-Z]+https://github.com/ShacharGal/hw5_2019.git.c')].reset_index()
    
    def fill_na_with_mean(self) -> Union[pd.DataFrame, np.ndarray]:
        """
        Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student. Returns the corrected DataFrame,
        as well as the row indices of the students that their new grades
        were generated.
        """
        grades = self.data.loc[:,'q1':'q5']
        has_na = np.where(grades.isna().any(axis=1))[0]
        grades = grades.T.fillna(grades.mean(axis=1)).T
        filled = self.data
        filled.loc[:,'q1':'q5'] = grades
        return filled, has_na

    def correlate_gender_age(self) -> pd.DataFrame:
        """
        Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.
        Returns a DataFrame with a MultiIndex containing the gender and whether
        the subject is above 40 years of age, and the average score in each of
        the five questions.
        """
        indexed = self.data.set_index([self.data.index, 'age', 'gender'])
        indexed_grades = indexed.loc[:,'q1':'q5']
        indexed_grades['over_40'] =  indexed_grades.index.get_level_values(1)>40
        return indexed_grades.groupby(['gender', 'over_40']).mean()